DROP TABLE IF EXISTS events;
CREATE TABLE events
(
id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
description LONGTEXT NOT NULL,
edate DATE,
vote INT DEFAULT 0,
valid BOOLEAN NOT NULL DEFAULT FALSE,
lat DOUBLE,
lng DOUBLE
);

DROP TABLE IF EXISTS tags;
CREATE TABLE tags
(
id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(40) NOT NULL
);

DROP TABLE IF EXISTS evetag;
CREATE TABLE evetag
(
id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
fk_id_event INT NOT NULL ,
fk_id_tag INT NOT NULL ,
FOREIGN KEY (fk_id_event) REFERENCES events(id),
FOREIGN KEY (fk_id_tag) REFERENCES evetag(id)
);
